version: "3.9"

services:
  real_sense_1:
    image: registry.screamtrumpet.csie.ncku.edu.tw/screamlab/pros_real_sense
    env_file:
      - .env
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
    privileged: true
    networks:
      - "compose_my_bridge_network"
    command: >
      ros2 launch realsense2_camera rs_launch.py
      camera_namespace:=real_sense_1
      serial_no:="\"239622301043\""
      camera_name:=D455
      usb_port_id:=2-2.2
      rgb_camera.color_profile:=1280x720x15
      depth_module.depth_profile:=1280x720x15
      depth_module.infra_profile:=1280x720x15

  real_sense_2:
    image: registry.screamtrumpet.csie.ncku.edu.tw/screamlab/pros_real_sense
    env_file:
      - .env
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
    privileged: true
    depends_on:
      - real_sense_1
    networks:
      - "compose_my_bridge_network"
    command: >
      ros2 launch realsense2_camera rs_launch.py
      camera_namespace:=real_sense_2
      serial_no:="\"419122270116\""
      camera_name:=D405
      usb_port_id:=2-2.3

  rosbridge:
    image: registry.screamtrumpet.csie.ncku.edu.tw/pros_images/pros_base_image:latest
    env_file:
      - .env
    networks:
      - "compose_my_bridge_network"
    ports:
      - 9090:9090
    command: "ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
networks:
  compose_my_bridge_network:
    driver: bridge
    external: true